accounts/urls.py
from django.conf.urls import include, url

from .forms import LoginForm
from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'registration/logout.html'}, name='logout'),
    url(r'^profile/$', include('core.urls'), name="splash"),
]

barkin_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
#    url(r'^profiles/', include('profiles.urls', namespace='profiles')),
    url(r'^barks/', include('barks.urls', namespace='barks')),
    url(r'^', include('core.urls', namespace='core')),
]

barks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^users/$', views.global_barks_list, name="global_barks_list"),
    url(r'^add/$', views.add_bark, name="add_bark"),
    url(r'^(?P<id>\d+)/$', views.barks_list, name="barks_list"),

#this may not work
    url(r'^(?P<id>\d+)/edit/$', views.edit_bark, name="edit_bark"),

#    url(r'^edit/(?P<id>\d+)/$', views.edit_bark, name="edit_bark"),
    url(r'^$', views.barks_list, name="barks_list"),
]

core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.splash, name="splash"),
]

profiles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^', views.profile_list, name="profile_list"),
    url(r'^(?P<id>\d+)/$', views.user_profile, name="user_profile"),
    ]

barks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

#from profiles.models import UserProfile

class Bark(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
#    profile = models.ForeignKey(UserProfile)
    content = models.CharField(max_length=60)
    post_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse("barks:edit_bark", args=[self.pk])

profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class getUser(User):
    pass

class UserProfile(models.Model):
    user = models.ForeignKey(User)
#   table has user_id now
    bio = models.CharField(max_length=200)
    url = models.URLField("Website", blank=True)
#   img_gravatar = ...

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
#from django.conf import settings
from django import forms

from core.forms import BootstrapFormMixin

class LoginForm(BootstrapFormMixin, AuthenticationForm):
    pass

class UserRegistrationForm(BootstrapFormMixin, forms.ModelForm):
    password = forms.CharField(label='Passphrase', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Passphrase', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data

        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passphrases are different!')

        return cd['password2']

barks/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Bark

class BarkForm(forms.ModelForm):

    class Meta:
        model = Bark
        fields = ('content',)

core/forms.py
from django.forms import widgets

class BootstrapFormMixin(object):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            if (isinstance(field.widget, widgets.TextInput) or isinstance(field.widget, widgets.Textarea) or isinstance(field.widget, widgets.SelectMultiple) or isinstance(field.widget, widgets.Select)):

                field.widget.attrs.update({
                    "class": "form-control"
                })

profiles/forms.py
from django import forms
from django.shortcuts import render, redirect

from .models import UserProfile

#url, bio, user_id
class ProfileForm(forms.ModelForm):
    pass

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegistrationForm

def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data["password"])

            new_user.save()
            messages.success(request, 'Congrats! You now exist.')

            return redirect('accounts:login')
    else:
        form = UserRegistrationForm()

    context = {
        "form": form,
    }

    return render(request, "accounts/register.html", context)

barks/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Bark
from .forms import BarkForm


def global_barks_list(request): #shows all user's barks
    ubs = Bark.objects.all()
    user_count = User.objects.count()

    context = {
        "ubs": ubs,
        "user_count": user_count,
    }

    return render(request, "barks/global_barks_list.html", context)

#@login_required #shows a specific user's barks
def barks_list(request, id=None):
    if id:
        user = User.objects.get(id=id)
        author = user
    else:
        user = request.user
        author = user

    bark_query = user.bark_set.all()

    context = {
        "author": author,
        "barks": bark_query,
    }
    return render(request, "barks/barks_list.html", context)

@login_required
def add_bark(request):
    if request.method == "POST":
        form = BarkForm(request.POST)

        if form.is_valid():
            new_bark = form.save(commit=False)
            new_bark.user = request.user

            new_bark.save()
            messages.success(request, "Bark!")
            return redirect('barks:barks_list', id=request.user.id)
    else:
        form = BarkForm()

    context = {
        "form": form,
    }

    return render(request, "barks/bark_form.html", context)

@login_required
def edit_bark(request, id=None):
    if id:
        bark = get_object_or_404(Bark, pk=id)

        #probably don't need this as @login_required?
        if bark.user != request.user:
            return HttpResponseForbidden()
    else:
        bark = Bark(request.user)

    form = BarkForm(request.POST, instance = bark) #here's the magic param
    if request.method == "POST":

        if form.is_valid():
            edited_bark = form.save(commit=False)
            edited_bark.user = request.user

            edited_bark.save()
            messages.success(request, "Bark, 'edit'!")
            return redirect('barks:barks_list', id=request.user.id)
    else:
        form = BarkForm()

    context = {
        "form": form,
        "bark": bark,
    }
    return render(request, "barks/edit_bark.html", context)

core/views.py
from django.shortcuts import render

def splash(request):
    return render(request, "core/index.html")

profiles/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .forms import ProfileForm
from .models import UserProfile

def profile_list(request):
    profile_set = UserProfile.objects.all()
    usernames = []
    for item in profile_set:
        usernames.append(request.user.username)

#    usernames = []
#    profile_set_length = len(profile_set)

#    if profile_set_length > 0:
#        for username in profile_set:
#            name = profile_set.get_username
#            usernames.append(name)
#    import pdb; pdb.set_trace()

#    else:
#        usernames.append("nothing here")
    context = {
        "profile_set": profile_set,
        "usernames": usernames,
    }

    return render(request, "profiles/profile_list.html", context)

def user_profile(request):
    user_profile = ProfileForm.objects.all()

    return render(request, "profiles/user_profile.html")

@login_required
def add_profile_info(request):
    if request.method == "POST":
        form = ProfileForm(request, POST)

    if form.is_valid():
        pass

accounts/templates/accounts/register.html
{% extends "core/base.html" %}

{% block content %}
<h2>Register page</h2>
<small>Please, fill out the boxes below to Register</small>
<hr>
<form action="{% url 'accounts:register' %}" method="POST">
{% csrf_token %}

{% for field in form %}
    {% include "core/_form_input.html" %}
{% endfor %}

<input type="hidden" name="next" value="{{next}}" />
<button type="submit" class="btn btn-warning">Submit</button>
</form> 

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %} 
                class="{{ message }}"
                {% endif %}>
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}

accounts/templates/register/login.html
{% extends "core/base.html" %}

{% block content %}
<h2>Login</h2>

    {% if form.errors %}
        <div class="alert alert-warning">
            Username and Passphrase don't match. Try again.
        </div>
    {% else %}
        <p>Fill out the form below to log in.</p>
    {% endif %}

    <form action="" method="POST">
        {% csrf token %}
        {% for field in form %}
            {{field}}

        {% endfor %}
        <input type="hidden" name="next" value="{{next}}"><button type="submit" class="btn btn-warning">Log in</button>
    </form>

{% endblock %}

barks/templates/barks/bark_form.html
{% extends "core/base.html" %}

{% block content %}
<h1>Add a Bark</h1>
<hr>

<div class="row">
    <div class="col-md-12">
        {% if form.errors %}
            <div class="alert alert-warning">
                Where's your bark??
            </div>
        {% else %}
            <h3>
                What you barkin' 'bout?
            </h3>
        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form action="" method="POST">
            {% csrf_token %}

            {% for field in form %}
                {% include "core/_form_input.html" %}
            {%  endfor %}
            <button type="submit" class="btn btn-warning btn-lg">Add Bark</button>
        </form>
    </div>
</div>
{% endblock content %}

barks/templates/barks/barks_list.html
{% extends "core/base.html" %}

{% block content %}
    <h1>{{ author }}'s barks list</h1>

    <ul>
        {% for bark in barks %}
            <li class="barkers-bark">
                {{ bark }} -- {{ bark.post_date }}
            </li>
            <li>
                <a href="{{ bark.get_absolute_url }}">Edit</a>
            </li>
        <hr style="border-top: 1px dotted black;">
        {% endfor %}
    </ul>

<a class="btn btn-warning btn-lg" href="{% url 'barks:add_bark' %}">Add a bark</a>

{% endblock content %}

barks/templates/barks/edit_bark.html
{% extends "core/base.html" %}

{% block content %}
<h1>Bark that edit!</h1>
<hr style="border-top: 2px dotted black;" />

<div class="row">
    <div class="col-md-6">
        <h2>Bark to edit:</h2>

        <p class="old-bark">
            {{ bark.content }}
        </p>
    </div>
    <div class="col-md-6">
        {% if form.errors %}
            <div class="alert alert-warning">
                There is no barked edit...there is only Zuul.
            </div>
            {% else %}
                <h2>Edit below:</h2>
        {% endif %}

        <form action="" method="POST">
            {% csrf_token %}

            {% for field in form %}
                {% include "core/_form_input.html" %}
            {%  endfor %}
            <button type="submit" class="btn btn-warning btn-lg">Confirm Edit</button>
        </form>
    </div>
</div>

{% endblock content %}

barks/templates/barks/global_barks_list.html
{% extends "core/base.html" %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>the Kennel<br />
            {% if user_count %}
                <small>There are {{user_count}} barkers on Barkin@pp!</small>
            {% else %}
                <small>There are 0 barkers on Barkin@pp!</small>
            {% endif %}
        </h1>

        <ul>
            <li>
                <a 
                    class="btn btn-warning btn-lg" 
                    href="{% url 'barks:add_bark' %}"
                >
                    Add a bark
                </a>
            </li>
        </ul>
    <!-- col-md-12 -->
    </div>
<!-- row -->
</div>
<hr>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        {% for bark in ubs %}
            <p class="barker-and-date">
            <a href="{% url 'barks:barks_list' bark.user_id %}"
                title="click to see all &nbsp; {{bark.user.username}}'s  barks"
            >
                {{bark.user.username}}</a>
                -- {{bark.post_date}}
            </p>
            <p class="barkers-bark">
                {{bark.content}}
            </p>
            <hr style="border-top: 1px dotted black;">
        {% endfor %}
    </div>
</div>
<!-- <span class="footer-buffer"></span> -->
{% endblock content %}

core/templates/core/_form_input.html
<div 
    {% if field.errors %}
        class="form-group has-error"
        {% else %}
            class="form-group"
        {% endif %}
>
    {{ field.label_tag }}
    {{ field }}

    {% if field.errors %}
        <span class="help-block">
            {% for error in field.errors %}
                {{error}}
            {% endfor %}
        </span>
    {% endif %}

</div>

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Barkin@pp
        {% endblock title %}
    </title>
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Quicksand" rel="stylesheet">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/a04d9e4c1c.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />

</head>
<body>
    <header>
        <nav class="navbar navbar-default navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#howdy" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <span>
                        <img src="{% static 'images/zynga-blue.png' %}" 
                            width="40px"
                            class="dog-brand">
                    </span>
                    <a class="navbar-brand" href="{% url 'core:splash' %}">
                        Barkin@pp
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="howdy">
                    <ul class="nav navbar-nav navbar-right">

                        {% if request.user.is_authenticated %}
                            <li role="presentation"
                                class="hello-user"
                            >
                                <a href="{% url 'barks:barks_list' request.user.id %}"
                                    title="Click to view your barks"
                                >
                                    <em>{{user}}'s Barks List</em>
                                </a>
                            </li>
                        {% else %}
                            <li role="presentation"
                                class="hello-user"
                            >
                                <a href="">
                                    <em>Hello! Guest</em>
                                </a>
                            </li>
                        {% endif %}

                        {% if request.user.is_authenticated %}
                            <li>
                                <a href="{% url 'accounts:logout' %}">Logout
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'accounts:login' %}" id="login">Login
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:register' %}" id="sign_up">Sign up
                                </a>
                            </li>
                        {% endif %}

                            <li role="presentation">
                                <a href="{% url 'barks:global_barks_list' %}"
                                    title="Check out what's barkin!"
                                >the Kennel
                                </a>
                            </li>

                    </ul>

                </div>
            </div>
        </nav>
    </header>
<div class="container">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <div class="aler alert-success">
            {{ message}}
            </div>
        {% endfor %}
    </ul>
    {% endif %}
    
    {% block content %}

    {% endblock content %}
    <span class="footer-buffer"></span>
</div>

<footer class="page-footer">
    <hr>
    <div class="aligned">
        <div>Icons made by <a href="http://www.flaticon.com/authors/simpleicon" title="SimpleIcon">SimpleIcon</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
        <span class="aligned">&copy; dark eyes design 2016</span>
    </div>
    <hr>
</footer>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
</script>

</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div class="jumbotron">
    <h1>
        <img src="{% static 'images/french-bulldog.png' %}" width="60px">
        &nbsp;Welcome to Barkin@pp!
    </h1>
</div>
<hr>
<div class="row">
    <div class="col-xs-12">
        <p>
            <div class="text-block">
                <p><strong>Barkin@pp</strong> is my take on a twitter-clone; it was designed during my time at Awesome Inc. U.'s 'Bootcamp' using Django as a 'Bootcamp' project.
                </p>

                <p>Feel free to <a href="{% url 'accounts:login' %}">Login</a> or <a href="{% url 'accounts:register' %}">Signup!
                    </a>
                </p>
            </div>
    </div>
</div>
{% endblock %}

core/templates/core/profile.html
{% extends "core/base.html" %}

{% block content %}
<h2>User Profile page</h2>
<hr>
{% if fields %}
    {% for field in fields %}
        {{field.label_tag}}
        {{field}}
    {% endfor %}
{% endif %}
{% endblock content %}

profiles/templates/profiles/profile_list.html
{% extends "core/base.html" %}

{% block content %}
    <h2>profiles list</h2>
    <hr>
    list of user profiles on Barkin@pp<br />
        
        {% for username in usernames %}

        {{username}}<br />

        {% endfor %}

{% endblock content %}

profiles/templates/profiles/user_profile.html
{% extends "core/base.html" %}

{% block content %}
<h2>User Profile page</h2>
<hr>
{% if fields %}
    {% for field in fields %}
        {{field.label_tag}}
        {{field}}
    {% endfor %}
{% endif %}
{% endblock content %}